### ISSUE TITLE
Invalid code on chained method calls on variables/method with e.g. `group` name

### ISSUE THREAD

**Issue by bquorning** [samphippen/rubyfmt#418] opened 2023-03-09 10:17 UTC
* Ruby version: 2.7.7
* Rubyfmt git sha: Not sha, but release 0.8.1.

## Input file

```ruby
group(:foo).bar
group.(:foo).bar
group.foo(:bar).baz
```

## Rubyfmt's output

```
group :foo.bar
group. :foo.bar
group.foo :bar.baz
```

## This breaks because

I don’t think rubyfmt should have changed my source code. I understand (from #358) that the parentheses were removed because it looks better in Bundler’s gemfiles, but when I use `group` as a _variable_ name, invalid code is produced. (The same problem happens if instead of `group` I use `it`, `describe`, `gem`, `source`, or `ruby`.)

A possible solution (with me having very little knowledge about rubyfmt’s internals) would be to check whether there are any method calls following the end-parenthesis before deciding whether it should be removed or not?

**Comment by reese** [comment] 2023-03-11 06:22
Closing this as a duplicate of #414, which has the same root cause, and both of these issues should be resolved by #415

**Closed as completed by reese** 2023-03-11 06:22 UTC
