### ISSUE TITLE
Changes code behavior on .split()?

### ISSUE THREAD

**Issue by nelson-vantage** [samphippen/rubyfmt#421] opened 2023-03-15 21:18 UTC
* Ruby version: 3.0.3
* Rubyfmt git sha: 266b47b (latest homebrew version)

## Input file

```ruby
if source.include?('something/')
	source.split('something/').last
end
```

## Rubyfmt's output

```ruby
if source.include?("something/")
  source.split "something/".last
end
```

## This breaks because

Expected `rubyfmt` to simply replace the single quotes with double quotes, but instead it left out the parens on the call to `#split` which changes the behavior of the program. 😨

**Comment by reese** [comment] 2023-03-15 21:59
Have you tested this on the current master branch? I'm fairly certain this is fixed by #415 and that this is a duplicate of #418 and #414.

**Comment by nelson-vantage** [comment] 2023-03-16 15:38
Ah, definitely a duplicate of the other issues. Can I push for a new release so others trying out `rubyfmt` aren't burnt by this? Any behavior change in formatted code generates a huge amount of distrust in the tool. 😬

**Comment by reese** [comment] 2023-03-16 21:17
(cc @fables-tales, might not be a bad idea to do a patch release since there are several other fixes on trunk now)

**Comment by reese** [comment] 2023-12-06 00:39
Doing some cleanup: this is now out in the most recent release (v0.10.0)

**Closed as completed by reese** 2023-12-06 00:39 UTC
