### ISSUE TITLE
Trailing comment in `def` block is moved to outside the block, leading comment in `def` block has incorrect spacing

### ISSUE THREAD

**Issue by lopopolo** [samphippen/rubyfmt#262] opened 2020-11-30 10:36 UTC
* Ruby version:

  ```console
  $ ruby -v
  ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin20]
  ```
* Rubyfmt git sha: 4b29c7041baaa6ecac758b982c641542dbe5e857

## Input file

```ruby
# frozen_string_literal: true

class Regexp
  def self.last_match(*args)
    # rubocop:disable Style/SpecialGlobalVars
    return nil if $~.nil?
    return $~ if args.empty?

    $~[*args]
    # rubocop:enable Style/SpecialGlobalVars
  end

  def self.try_convert(obj = nil)
    raise ArgumentError if obj.nil?
    return obj if obj.is_a?(Regexp)

    obj.to_regexp
  rescue StandardError
    nil
  end

  def ~
    self =~ $_ # rubocop:disable Style/SpecialGlobalVars
  end
end
```

## Rubyfmt's output

```ruby
# frozen_string_literal: true

class Regexp
  def self.last_match(*args)
  # rubocop:disable Style/SpecialGlobalVars
    return nil if $~.nil?
    return $~ if args.empty?

    $~[*args]
  end

  # rubocop:enable Style/SpecialGlobalVars
  def self.try_convert(obj = nil)
    raise ArgumentError if obj.nil?
    return obj if obj.is_a?(Regexp)

    obj.to_regexp
  rescue StandardError
    nil
  end

  def ~
    # rubocop:disable Style/SpecialGlobalVars
    self =~ $_
  end
end
```

## This breaks because

Rubyfmt changes documentation in a surprising way, RuboCop comments may not have the desired effect.

**Comment by fables-tales** [comment] 2021-05-31 20:00
This was fixed in V0.6.7 (it's a dupe of #295 )

**Closed as completed by fables-tales** 2021-05-31 20:00 UTC
